version: "3.8"

services:
  postgres:
    image: postgres:16.8
    container_name: postgres-desafio
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafiovotacao
    ports:
      - "5432:5432"
#    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql