spring:
  application:
    name: desafiovotacao
  datasource:
    url: jdbc:postgresql://localhost:5432/desafiovotacao
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
